#!/usr/bin/env node

/**
 * Setup Wizard for Volunteer Platform
 * 
 * This interactive script helps you set up your environment and database.
 * Run: node scripts/setup-wizard.js
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

function generateJWTSecret() {
  const crypto = require('crypto');
  return crypto.randomBytes(32).toString('base64');
}

async function main() {
  console.log('\n🚀 Volunteer Platform Setup Wizard\n');
  console.log('This wizard will help you set up your environment and database.\n');

  // Check if .env.local exists
  const envPath = path.join(process.cwd(), '.env.local');
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('\n📝 Environment Variables Setup\n');

  // MongoDB URI
  console.log('MongoDB Atlas Setup:');
  console.log('1. Go to https://www.mongodb.com/cloud/atlas');
  console.log('2. Create a free account and cluster');
  console.log('3. Create a database user');
  console.log('4. Whitelist IP: 0.0.0.0/0 (for development)');
  console.log('5. Get your connection string\n');

  const mongoUri = await question('Enter your MongoDB URI (or press Enter to skip): ');
  
  // JWT Secret
  const generateSecret = await question('\nGenerate JWT Secret automatically? (Y/n): ');
  let jwtSecret;
  
  if (generateSecret.toLowerCase() !== 'n') {
    jwtSecret = generateJWTSecret();
    console.log(`✅ Generated JWT Secret: ${jwtSecret.substring(0, 20)}...`);
  } else {
    jwtSecret = await question('Enter your JWT Secret (min 32 characters): ');
    if (jwtSecret.length < 32) {
      console.log('⚠️  Warning: JWT Secret should be at least 32 characters for security.');
    }
  }

  // Node Environment
  const nodeEnv = await question('\nNode Environment (development/production) [development]: ') || 'development';

  // Email Configuration (Optional)
  console.log('\n📧 Email Configuration (Optional - press Enter to skip)');
  const smtpHost = await question('SMTP Host [smtp.gmail.com]: ') || 'smtp.gmail.com';
  const smtpPort = await question('SMTP Port [587]: ') || '587';
  const smtpSecure = await question('SMTP Secure (true/false) [false]: ') || 'false';
  const smtpUser = await question('SMTP User (email): ');
  const smtpPass = await question('SMTP Password (app password for Gmail): ');
  const smtpFrom = await question('SMTP From Address: ');

  // Setup Secret Token (for API endpoints)
  const setupToken = await question('\n🔐 Setup Secret Token (for database initialization API, or press Enter to skip): ');

  // Build .env.local content
  let envContent = `# Environment Variables
# Generated by setup wizard on ${new Date().toISOString()}

# MongoDB Configuration
MONGODB_URI=${mongoUri || 'mongodb+srv://username:password@cluster.mongodb.net/volunteer-platform?retryWrites=true&w=majority'}

# JWT Secret
JWT_SECRET=${jwtSecret}

# Node Environment
NODE_ENV=${nodeEnv}
`;

  if (smtpUser) {
    envContent += `
# Email Configuration
SMTP_HOST=${smtpHost}
SMTP_PORT=${smtpPort}
SMTP_SECURE=${smtpSecure}
SMTP_USER=${smtpUser}
SMTP_PASS=${smtpPass}
${smtpFrom ? `SMTP_FROM=${smtpFrom}` : ''}
`;
  }

  if (setupToken) {
    envContent += `
# Setup Secret Token (for database initialization API)
SETUP_SECRET_TOKEN=${setupToken}
`;
  }

  // Write .env.local
  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ Created .env.local file');

  // Ask about database initialization
  if (mongoUri && mongoUri.includes('mongodb')) {
    const initDb = await question('\n📊 Initialize database now? (y/N): ');
    if (initDb.toLowerCase() === 'y') {
      try {
        console.log('\nInitializing database...');
        execSync('npm run init-db', { stdio: 'inherit' });
        console.log('✅ Database initialized');
      } catch (error) {
        console.error('❌ Error initializing database:', error.message);
      }
    }

    // Ask about creating admin user
    const createAdmin = await question('\n👤 Create admin user now? (y/N): ');
    if (createAdmin.toLowerCase() === 'y') {
      const adminEmail = await question('Admin Email: ');
      const adminPassword = await question('Admin Password: ');
      const adminName = await question('Admin Name: ');

      if (adminEmail && adminPassword && adminName) {
        try {
          console.log('\nCreating admin user...');
          execSync(`npm run create-admin "${adminEmail}" "${adminPassword}" "${adminName}"`, { stdio: 'inherit' });
          console.log('✅ Admin user created');
        } catch (error) {
          console.error('❌ Error creating admin user:', error.message);
        }
      }
    }
  }

  console.log('\n✅ Setup complete!');
  console.log('\nNext steps:');
  console.log('1. Review .env.local and update any values if needed');
  console.log('2. Run: npm run dev');
  console.log('3. Visit: http://localhost:3000\n');

  rl.close();
}

main().catch(console.error);

